//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chk_info
    {
        public int pkid { get; set; }
        public int medical_id { get; set; }
        public int patient_id { get; set; }
        public int chk_type_id { get; set; }
        public int chk_demo_id { get; set; }
        public string chk_result { get; set; }
        public int fileid { get; set; }
    }
}
