//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chk_demo_value
    {
        public int pkid { get; set; }
        public int chk_demo_id { get; set; }
        public string chk_value1_min { get; set; }
        public string chk_value1_max { get; set; }
        public string chk_value1_remark { get; set; }
        public string chk_value2_min { get; set; }
        public string chk_value2_max { get; set; }
        public string chk_value2_remark { get; set; }
        public string gender { get; set; }
        public int age_stage { get; set; }
        public string chk_method { get; set; }
        public string chk_sample { get; set; }
    }
}
