//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dr_visit_detail
    {
        public int pkid { get; set; }
        public int visit_id { get; set; }
        public int visit_type { get; set; }
        public int patient_id { get; set; }
        public string patient_name { get; set; }
        public System.DateTime service_date { get; set; }
        public string service_time { get; set; }
        public string remarks { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
