//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_check
    {
        public int pkid { get; set; }
        public string file_path { get; set; }
        public int patient_id { get; set; }
        public int file_type { get; set; }
        public int check_status { get; set; }
        public System.DateTime check_time { get; set; }
        public string check_remark { get; set; }
        public string check_user { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
