//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class md_bank
    {
        public int pkid { get; set; }
        public string bank { get; set; }
        public string card_no { get; set; }
        public string card_person { get; set; }
        public System.DateTime createtime { get; set; }
        public string bank_remark { get; set; }
    }
}
