//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class md_docter
    {
        public int pkid { get; set; }
        public int hispital_id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string title { get; set; }
        public string position { get; set; }
        public string cust_name { get; set; }
        public string sub_name { get; set; }
        public string birthday { get; set; }
        public string contact_tel { get; set; }
        public string login_pwd { get; set; }
        public System.DateTime createtime { get; set; }
        public decimal current_income { get; set; }
        public string photo { get; set; }
    }
}
