//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class md_druginfo
    {
        public int pkid { get; set; }
        public string drugcode { get; set; }
        public string drugname { get; set; }
        public string commonname { get; set; }
        public string standard { get; set; }
        public string authno { get; set; }
        public int producerid { get; set; }
        public string cust_name { get; set; }
        public string sub_name { get; set; }
        public decimal use_num { get; set; }
        public int use_daynum { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
