//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_druguse_suggest_rcd
    {
        public int pkid { get; set; }
        public int druguse_suggest_id { get; set; }
        public int drugid { get; set; }
        public decimal use_num { get; set; }
        public string use_type { get; set; }
    }
}
