//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_info
    {
        public int pkid { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string cardtype { get; set; }
        public string cardno { get; set; }
        public System.DateTime birthday { get; set; }
        public System.DateTime createtime { get; set; }
        public string login_pwd { get; set; }
    }
}
