//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_message
    {
        public int pkid { get; set; }
        public int patientid { get; set; }
        public int drid { get; set; }
        public int status { get; set; }
        public string contents { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
