//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_address
    {
        public int pkid { get; set; }
        public string contact_tel { get; set; }
        public string contact_add { get; set; }
        public string contact_mobile { get; set; }
        public bool isdefault { get; set; }
        public int patient_id { get; set; }
    }
}
