//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion_events
    {
        public int pkid { get; set; }
        public string name { get; set; }
        public string contents { get; set; }
        public int hospital_id { get; set; }
        public int face_type { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string attachfile { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
